id: IE44109E0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:45:36+00:00'
last_modified: '2022-06-08T08:03:55.489662+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25199
  title: རྩྭ་ཐང་མེ་ཏོག་གི་དྲི་ཞིམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    51C6:
      image_group_id: I1KG10362
      title: ''
      total_pages: 518
      order: 1
      base_file: 51C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
