id: P008226
initial_creation_type: ocr
source_metadata:
  id: bdr:W25199
  title: རྩྭ་ཐང་མེ་ཏོག་གི་དྲི་ཞིམ།
  author: ''
  volumes:
    db7a2f0cc3264a52b9455a9478fd5749:
      image_group_id: I1KG10362
      title: ''
      volume_number: 1
      total_pages: 518
