id: P008226
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:09:07.680457
source_metadata:
  id: bdr:W25199
  title: རྩྭ་ཐང་མེ་ཏོག་གི་དྲི་ཞིམ།
  author: ''
  volumes:
    db7a2f0cc3264a52b9455a9478fd5749:
      image_group_id: I1KG10362
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
